! r3 - net_c 와 net_a 에 연결
frr defaults traditional
hostname r3
!
interface lo
 ip address 10.255.0.3/32
!
interface eth0
 description transit (discover actual shared subnet with measure_ospf.py)
 ip ospf cost 10
!
interface eth1
 description transit (discover actual shared subnet with measure_ospf.py)
 ip ospf cost 10
!
router ospf
 ospf router-id 3.3.3.3
 network 0.0.0.0/0 area 0
!
line vty
